import "./globals.css";
import { Toaster } from "react-hot-toast";


export const metadata = {
  title: "ArcTeam",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl" >
      <body
        className={`antialiased`} suppressHydrationWarning
      >
        {children}
        <Toaster position="bottom-center" />
      </body>
    </html>
  );
}
